export const meta = {
  name: 'spec-sheet',
  description: 'Draft the pursuit spec sheet (locked numbers, approved proofs, preferred references, ranked stories, quotes, unmatchable fact, gap decisions, page/device budgets, win-theme evidence map, concession policy) from three angles, judge, synthesize, render a decision docx for approval',
  phases: [
    { title: 'Draft', detail: 'three Fable drafts: evaluator-first, proof-first, story-first' },
    { title: 'Judge', detail: 'each draft scored by two judges' },
    { title: 'Synthesize', detail: 'one spec sheet; render decision docx' },
  ],
}
// args: { wiki, pursuit, pursuitFile, reqsDir, tripDigest, contentPlan, outDir }
const W = args.wiki, P = args.pursuit
const out = args.outDir || `${W}\\pursuits\\${P}`
const contentPlan = args.contentPlan || `${W}\\pursuits\\${P}\\content-plan.md`
const SPEC = { type:'object', properties:{ path:{type:'string'}, angle:{type:'string'}, locked_numbers:{type:'number'}, proof_points:{type:'number'}, references:{type:'array', items:{type:'string'}}, stories:{type:'array', items:{type:'string'}}, closer:{type:'string'}, gap_decisions:{type:'number'}, open_decisions:{type:'array', items:{type:'string'}}, summary:{type:'string'} }, required:['path','angle','summary'] }
const SCORES = { type:'object', properties:{ draft:{type:'string'}, scores:{type:'object'}, mean:{type:'number'}, strengths:{type:'array', items:{type:'string'}}, gaps:{type:'array', items:{type:'string'}} }, required:['draft','scores','mean'] }
const DONE = { type:'object', properties:{ files:{type:'array', items:{type:'string'}}, summary:{type:'string'}, decisions_for_michael:{type:'array', items:{type:'string'}} }, required:['files','summary'] }
const inputs = `Pursuit file: ${args.pursuitFile}. Content plan: ${contentPlan} — the approved list of topics per section (ticked ☑ = in scope, ☐ = out; "lead" rows carry the section's opener or closer); lock numbers, proofs, references and stories only for ticked topics, and never plan content for an unticked one. Requirements per section: ${args.reqsDir}\\*.md (read all eight). Trip-report digest: ${args.tripDigest}. Content bank: proof-point registry ${W}\\proof-points\\registry.md and .json; testimonials ${W}\\testimonials\\inventory.md; stories ${W}\\stories\\catalog.md; faceted index ${W}\\wiki\\index.md; blocks under ${W}\\wiki\\; verbatim prose under ${W}\\verbatim\\<slug>\\pages\\. Voice guide ${W}\\voice\\voice-guide.md. Prior pilot diagnostics: C:\\Users\\micha\\Desktop\\Richmond\\Draft Sections\\02 Claude Working Drafts\\_work\\editorial_log_03.md and fp_03_qualifications.md (for the list of numeric conflicts and gaps already found).`
const template = `Spec sheet sections, in this order, every row traceable to a registry/testimonial/story id or a pursuit document:
1 Locked number sheet — one row per figure the proposal will state (revenue, O&M revenue, backlog, renewal rate, NPDES compliance %, TRIR/EMR/DART, facilities/clients/miles counts, California tenures, reference plant sizes/miles/fees, entity dates), columns: id | claim | LOCKED value | competing values seen (with source) | owner to confirm | status (locked | needs-owner).
2 Approved proof points — outcome proofs the writers may use (savings, complaint reductions, enforcement resolved, energy cuts, callouts eliminated, awards), each with id, exact wording, source page, external-use status (approved | client-permission-needed | internal-only), and which section(s) it is assigned to.
3 Preferred reference set — five references + two bench, each with one-line reason tied to Richmond (California, 5–20 MGD activated sludge with primary clarifiers, collection + stormwater scope, odor, regulatory settlement/enforcement, incumbent displacement), what each must prove, and permission/contact status.
4 House stories, ranked — top 8 with the beat, proof ids, section assignment; name "the closer" for the Executive Summary and for Qualifications.
5 Quotable inventory — every quote the proposal may print: text, attribution, permission status; quotes without permission are listed as NOT PRINTABLE until confirmed.
6 The unmatchable fact — Mack Mckenzie's Richmond WPCP tenure: exact wording allowed, placement rule (first 100 words of Qualifications and Executive Summary, boxed), and the decision needed (role/availability).
7 Gap decisions — every known gap (Waterbury 55% odor figure, NexGen/OKC experience, stormwater collection-system reference, bonding/surety data, California principal office, Clovis/West Basin fees, current TRIR/EMR/DART, 10-year litigation list, reference permissions, Bay Area offices/staff, contracting entity, signatories) with a decision: DROP | SOURCE BY <date, owner> | WRITE AROUND <exact approach>, so no placeholder reaches body text.
8 Page and device budget per section — for §8.4.1–8.4.7: pages, tables max, stat rows, fact boxes, pull quotes, figures, callouts; reference detail tables to appendix or body.
9 Win-theme evidence map — for each of the seven Directive win themes × each section: the proof ids and story ids that carry it and the device used; mark themes with no proof as "needs source".
10 Concession policy — what may be admitted (e.g., West Basin tenure since 2025), how, and what must never be volunteered.
11 Decisions table — every item that needs Michael's or the pursuit team's decision, one line each, with a default recommendation.`

phase('Draft')
const angles = [
  ['evaluator-first', 'start from the RFP evaluation criteria and the 254 requirements; decide what proof each scored section needs to win maximum points'],
  ['proof-first', 'start from the registry and the verbatim proposals; decide which numbers and outcomes are strongest and safest, then assign them'],
  ['story-first', 'start from the story catalog and trip-report hot buttons; decide the narrative arc of the whole proposal and the closer for each section, then back it with proof'],
]
const drafts = (await parallel(angles.map(([angle, how]) => () => agent(`Draft the pursuit SPEC SHEET for ${P}. Angle: ${angle} — ${how}. ${inputs}\n${template}\nRules: never invent a number — every value is copied from the registry, a verbatim page, or a pursuit document with its source; where sources conflict, list all values and recommend the lock with a reason; where nothing exists, write a gap decision. Write to ${out}\\_drafts\\spec_${angle}.md. Return path, angle, counts, the five references, top stories, the closer, open decisions, summary.`, {model:(args.model||'fable'), effort:'high', phase:'Draft', label:`spec: ${angle}`, schema:SPEC})))).filter(Boolean)

phase('Judge')
const scores = (await parallel(drafts.flatMap(d => ['proposal-manager','capture-lead'].map(j => () => agent(`Judge a pursuit spec-sheet draft as the ${j} (${j==='proposal-manager' ? 'you must run writers off this sheet for seven sections in three weeks; judge completeness, precision, traceability, and whether a writer could work without asking questions' : 'you own the win strategy; judge whether the choices (references, stories, closer, concessions, theme map) would beat the incumbent in front of this City'}). Draft: ${d.path}. ${inputs}\nScore 1–10 on: traceability, completeness vs the 11-section template, strategic fit to Richmond hot buttons, gap handling (no placeholders left for writers), device/page budgets realism, and overall. List strengths and gaps.`, {model:(args.model||'fable'), effort:'high', phase:'Judge', label:`judge ${d.angle} / ${j}`, schema:SCORES}))))).filter(Boolean)
log(`Spec drafts scored: ${drafts.map(d => `${d.angle}=${(scores.filter(s=>s.draft.includes(d.angle)).reduce((a,s)=>a+s.mean,0)/Math.max(1,scores.filter(s=>s.draft.includes(d.angle)).length)).toFixed(2)}`).join(', ')}`)

phase('Synthesize')
const final = await agent(`Synthesize the FINAL spec sheet for ${P} from the three drafts and their judgments. Drafts: ${JSON.stringify(drafts.map(d=>({path:d.path, angle:d.angle})))}. Judgments: ${JSON.stringify(scores)}. ${inputs}\n${template}\nTake the most complete and best-sourced content for each of the 11 sections; resolve disagreements between drafts explicitly (state the choice and why); make sure every gap has a decision and every number has an id and source. Write ${out}\\spec-sheet.md with frontmatter (pursuit, version: 1, status: draft-for-approval, date: 2026-09-05). Then write ${out}\\spec-sheet.json (machine-readable: locked_numbers[{id, claim, value, unit, source}], proof_points[], references[], stories[], quotes[], gaps[{item, decision, how, owner, by}], budgets{section:{pages, tables, stats, factboxes, quotes, figures, callouts}}, theme_map{theme:{section:[ids]}}, concessions[], decisions[]). Then render the approval document: convert spec-sheet.md to ${out}\\Richmond_Spec_Sheet_v1_FOR_APPROVAL.docx with python "${W}\\work\\build_docx.py" "${out}\\spec-sheet.md" "${out}\\Richmond_Spec_Sheet_v1_FOR_APPROVAL.docx" --section-label "Pursuit spec sheet v1" --header "City of Richmond — WPCP, Collection and Stormwater O&M" --notes-inline, after appending to the markdown a final section "## Decisions — tick one per row" rendered as a GFM table with columns Item | Recommendation | ☐ Approve | ☐ Change (note) so Michael can mark it in Word. Return files, summary, and the list of decisions for Michael.`, {model:(args.model||'fable'), effort:'max', phase:'Synthesize', label:'final spec sheet', schema:DONE})
return { drafts: drafts.map(d=>({angle:d.angle, summary:d.summary})), scores: scores.map(s=>({draft:s.draft, mean:s.mean})), final }
