export const meta = {
  name: 'write-section',
  description: 'Write one proposal section to top-writer standard: brief → 4 angle drafts (Fable max) → judge panel → synthesis → adversarial reviewers (client evaluator, incumbent, compliance, fact-check, metrics) → revise loop → render',
  phases: [
    { title: 'Brief', detail: 'Opus compiles the section brief from spec sheet, voice guide, requirements, bank' },
    { title: 'Draft', detail: 'four independent Fable drafts from different angles', model: 'fable' },
    { title: 'Judge', detail: 'Fable judges score every draft on the rubric' },
    { title: 'Synthesize', detail: 'Fable grafts the best of each into one draft' },
    { title: 'Attack', detail: 'client evaluator, incumbent, compliance, fact-check, metrics; revise until thresholds pass' },
    { title: 'Render', detail: 'docx + notes companion + validator' },
  ],
}
// args: { wiki, pursuit, section:{id, title, rfpSection, reqsFile, budgetPages, outDir, outStem}, voiceGuide, rubric, spec, registry, testimonials, stories, index, extraSources:[paths], sectionLabel, headerText }
const W = args.wiki, S = args.section
// Profile knobs (see HANDOFF-writing.md): full = 4 angles / 3 judges / 3 rounds; lean = 2 / 2 / 2
const N_ANGLES = args.angles || 4, N_JUDGES = args.judges || 3, MAX_ROUNDS = args.maxAttackRounds || 3
const JUDGE_MODEL = args.judgeModel || args.writerModel || 'fable', SYNTH_MODEL = args.synthModel || args.writerModel || 'fable'
const paths = { voice: args.voiceGuide || `${W}\\voice\\voice-guide.md`, rubric: args.rubric || `${W}\\voice\\rubric.json`, spec: args.spec || `${W}\\pursuits\\${args.pursuit}\\spec-sheet.md`, plan: args.contentPlan || `${W}\\pursuits\\${args.pursuit}\\content-plan.md`, registry: args.registry || `${W}\\proof-points\\registry.json`, testimonials: args.testimonials || `${W}\\testimonials\\inventory.md`, stories: args.stories || `${W}\\stories\\catalog.md`, index: args.index || `${W}\\wiki\\index.md` }
const work = `${S.outDir}\\_work\\${S.id}`

const BRIEF = { type:'object', properties:{ brief_path:{type:'string'}, must_answer:{type:'array', items:{type:'string'}}, proof_ids:{type:'array', items:{type:'string'}}, stories:{type:'array', items:{type:'string'}}, quotes_allowed:{type:'array', items:{type:'string'}}, device_budget:{type:'object'}, gaps:{type:'array', items:{type:'string'}}, summary:{type:'string'} }, required:['brief_path','must_answer','proof_ids','summary'] }
const DRAFT = { type:'object', properties:{ path:{type:'string'}, angle:{type:'string'}, words_prose:{type:'number'}, proof_ids_used:{type:'array', items:{type:'string'}}, stories_used:{type:'array', items:{type:'string'}}, devices:{type:'object'}, notes:{type:'string'} }, required:['path','angle','words_prose','proof_ids_used'] }
const SCORES = { type:'object', properties:{ draft:{type:'string'}, scores:{type:'object'}, mean:{type:'number'}, best_passages:{type:'array', items:{type:'string'}}, worst_passages:{type:'array', items:{type:'string'}}, rationale:{type:'string'} }, required:['draft','scores','mean'] }
const REVIEW = { type:'object', properties:{ reviewer:{type:'string'}, verdict:{type:'string', enum:['pass','fail']}, findings:{type:'array', items:{type:'object', properties:{ location:{type:'string'}, severity:{type:'string', enum:['blocker','major','minor']}, issue:{type:'string'}, fix:{type:'string'} }, required:['location','severity','issue','fix']}}, summary:{type:'string'} }, required:['reviewer','verdict','findings'] }
const FACTS = { type:'object', properties:{ reviewer:{type:'string'}, verdict:{type:'string', enum:['pass','fail']}, claims_checked:{type:'number'}, unsupported:{type:'array', items:{type:'object', properties:{ text:{type:'string'}, reason:{type:'string'}, fix:{type:'string'} }}}, quotes_without_permission:{type:'array', items:{type:'string'}}, summary:{type:'string'} }, required:['reviewer','verdict','claims_checked','unsupported'] }
const METRICS = { type:'object', properties:{ reviewer:{type:'string'}, verdict:{type:'string', enum:['pass','fail']}, metrics:{type:'object'}, failing:{type:'array', items:{type:'string'}}, summary:{type:'string'} }, required:['reviewer','verdict','metrics','failing'] }
const RENDER = { type:'object', properties:{ docx:{type:'string'}, notes_docx:{type:'string'}, pages:{type:'number'}, validator:{type:'object'}, summary:{type:'string'} }, required:['docx','pages','summary'] }

const common = `Section: ${S.title} (RFP ${S.rfpSection}) for the ${args.pursuit} pursuit. Inputs: content plan ${paths.plan} (read the table under this section's heading: every ☑ topic is covered, every ☐ topic is left out, a "lead" topic carries the opener or closer, a "brief" topic gets one paragraph or a table row; the block path in the Source column is the preferred wiki block for that topic); spec sheet ${paths.spec} (LOCKED — obey it: locked numbers, approved proof points, preferred references, ranked stories and the closer, quotable inventory with permission, the unmatchable fact and its placement, gap decisions, page/device budget, win-theme evidence map, concession policy); voice guide ${paths.voice}; rubric ${paths.rubric}; requirements ${S.reqsFile}; proof registry ${paths.registry}; testimonials ${paths.testimonials}; stories ${paths.stories}; bank index ${paths.index} (blocks under ${W}\\wiki\\, verbatim prose under ${W}\\verbatim\\<slug>\\pages\\).${(args.extraSources||[]).length ? ' Pursuit sources: ' + args.extraSources.join(' ; ') : ''} Page budget: ${S.budgetPages} pages at 12pt. Output markdown schema: "# Title", one italic deck line, "## n.n Assertion-style heading", GFM tables preceded by "Table n-n. Caption", devices on their own lines: "> STAT: number | label" (up to 4 consecutive), "> QUOTE: \\"text\\" — Speaker, Title, Org", "> FACTBOX: Title | line | line", "> CALLOUT: text", "[FIGURE n-n: caption — what it shows]". Body text carries NO placeholders, [VERIFY], internal notes, or bracketed hedges — open items go under a final "## Draft notes" section which is rendered to a separate companion file.`

phase('Brief')
const brief = await agent(`Compile the writer's brief for one proposal section. ${common}
Read everything listed. Write ${work}\\brief.md containing: (0) the ticked topics from the content plan for this section, in order, each with its mark (lead / include / brief) and preferred block; (1) the evaluator's scoring lens for this section (weight, what the RFP says it evaluates); (2) every requirement the section must answer, each with the assertion-style heading it will live under and the proof/story assigned to it; (3) the locked numbers and proof ids available (values copied exactly from the spec sheet); (4) the stories to tell, in order, with the beat of each and the verbatim page to read; (5) quotes with permission on-file (exact text, attribution); (6) the unmatchable fact and where it goes; (7) win-theme evidence map for this section (theme → proof → device); (8) device budget (tables max, stats, factboxes, quotes, figures, callouts); (9) gap decisions in force (DROP / WRITE AROUND how); (10) the 15 most relevant verbatim passages from the bank (path + ¶ + the text) that a writer should adapt — prefer preferred/house-favorite blocks; (11) anti-patterns from the voice guide the pilot fell into. Return the path and structured fields.`, {model:'opus', effort:'medium', phase:'Brief', label:'brief', schema:BRIEF})

phase('Draft')
const ANGLES = [
  ['story-first', 'Open with the strongest story (the closer or the unmatchable fact), let proof follow narrative; every subsection is a short story with an outcome.'],
  ['proof-first', 'Lead every subsection with the hardest number and its consequence for the client; stat rows and fact boxes carry the argument; prose connects them.'],
  ['evaluator-first', 'Write for the scorer: every requirement answered in the order asked under an assertion heading that also carries the RFP wording, each with proof, so the section scores maximum points with zero hunting.'],
  ['incumbent-displacement', 'Write for a client that is leaving an incumbent it distrusts: transparency, what changes on day one, what they will see and when, proof from prior displacements and testimonials, honest concessions per the concession policy.'],
]
const drafts = (await parallel(ANGLES.slice(0, N_ANGLES).map(([angle, instr]) => () => agent(`You are the lead writer. Write the complete section as a full draft in markdown. ${common}
Brief: ${brief.brief_path} — read it first, then the voice guide, then the spec sheet; then read the verbatim passages the brief points to. Angle: ${angle} — ${instr}
Standards: this must read like the winning proposals in the verbatim layer, not like a compliance document. Every subsection opens with the client's outcome. Every number carries its consequence. Win themes recur in identical words. At least three proof devices per page. Sentences median 18–25 words with deliberate short punches. Headings are assertions. The client is named in nearly every paragraph. Nothing a competitor could ship unchanged. Use only numbers present in the spec sheet's locked values or the registry (cite the id in an HTML comment <!-- PP-0012 --> after the sentence — comments are stripped at render). Use only quotes with permission on-file (cite <!-- TM-0003 -->). Obey gap decisions: never invent, never hedge in body text. Length: within the page budget (≈ ${Math.round(S.budgetPages*380)} prose words plus devices). Write to ${work}\\draft_${angle}.md. Return path, angle, prose word count, proof ids used, stories used, device counts.`, {model:(args.writerModel||'fable'), effort:'max', phase:'Draft', label:`draft: ${angle}`, schema:DRAFT})))).filter(Boolean)
log(`Drafts: ${drafts.map(d=>`${d.angle} ${d.words_prose}w`).join(' | ')}`)

phase('Judge')
const JUDGES = ['city-evaluator', 'senior-proposal-writer', 'competitor-strategist']
const scores = (await parallel(drafts.flatMap(d => JUDGES.slice(0, N_JUDGES).map(j => () => agent(`Score one section draft with the rubric ${paths.rubric}, applying the voice guide ${paths.voice} and the spec sheet ${paths.spec}. Persona: ${j} (${j==='city-evaluator' ? 'you sit on the City selection committee and score against the RFP criteria; you have read the incumbent\'s proposal too' : j==='senior-proposal-writer' ? 'you have written and won dozens of O&M proposals; you judge craft, voice, and whether a top writer would sign it' : 'you work for the incumbent; you judge where this draft beats you and where you would attack it'}). Draft: ${d.path}. Score every rubric dimension 1–10 with one-sentence justification, compute the mean, quote the 3 best and 3 worst passages, and give a 5-line rationale. Independent — do not read other drafts.`, {model:JUDGE_MODEL, effort:'high', phase:'Judge', label:`judge ${d.angle} / ${j}`, schema:SCORES}))))).filter(Boolean)
const ranked = drafts.map(d => ({ d, mean: scores.filter(s => s.draft.includes(d.angle) || s.draft===d.path).reduce((a,s)=>a+s.mean,0) / Math.max(1, scores.filter(s => s.draft.includes(d.angle) || s.draft===d.path).length) })).sort((a,b)=>b.mean-a.mean)
log(`Ranking: ${ranked.map(r=>`${r.d.angle} ${r.mean.toFixed(2)}`).join(' > ')}`)

phase('Synthesize')
let current = await agent(`Synthesize the final section draft. ${common}
Drafts and judge scores: ${JSON.stringify(ranked.map(r=>({path:r.d.path, angle:r.d.angle, mean:r.mean})))}. Full judge output: ${JSON.stringify(scores)}. Start from the top-ranked draft's structure; graft in the best passages the judges quoted from the others; remove anything any judge marked worst unless another judge marked it best. Re-read the voice guide and spec sheet before you finish. Keep proof-id and testimonial-id HTML comments. Write to ${work}\\draft_synthesis_r0.md. Return path, angle "synthesis", prose word count, proof ids used, stories used, device counts.`, {model:SYNTH_MODEL, effort:'max', phase:'Synthesize', label:'synthesis', schema:DRAFT})

phase('Attack')
const passes = (r) => r.every(x => x && x.verdict === 'pass')
let round = 0, reviews = []
for (; round < MAX_ROUNDS; round++) {
  reviews = await parallel([
    () => agent(`You are the City of Richmond Public Works evaluator reading this section against the RFP requirements (${S.reqsFile}) and your own frustrations with the incumbent. Draft: ${current.path}. Find every place you would deduct points, be unconvinced, or see an unanswered requirement; every place the draft talks about the vendor when it should talk about you; every claim without a consequence for the City. Verdict pass only if you would score it at the top of the range. Spec sheet for context: ${paths.spec}.`, {model:JUDGE_MODEL, effort:'high', phase:'Attack', label:`r${round} city evaluator`, schema:REVIEW}),
    () => agent(`You are the incumbent's capture lead (Veolia) reading the competitor's section: ${current.path}. Where do you answer this better in your own proposal? Where is a claim vulnerable, generic, or unproven? Where does the draft concede something it did not need to, or fail to make a concession the evaluator will notice? List each as a finding with the fix that would take the attack away. Verdict pass only if you have no unaddressed line of attack.`, {model:JUDGE_MODEL, effort:'high', phase:'Attack', label:`r${round} incumbent`, schema:REVIEW}),
    () => agent(`Compliance check. Requirements file ${S.reqsFile} lists every RFP requirement (IDs) this section must answer. Draft: ${current.path}. For each ID: ADDRESSED under which heading with a ≤15-word quote, PARTIAL (which element missing), or MISSING. Also check body text for any of: [PLACEHOLDER, [VERIFY, [CONFIRM, [TBD, [CLIENT], Hull, Santa Monica, SWIP; and headings that are bare RFP labels without an assertion. Verdict pass only if every ID is ADDRESSED and the checks are clean.`, {model:'sonnet', effort:'low', phase:'Attack', label:`r${round} compliance`, schema:REVIEW}),
    () => agent(`Fact check. Draft: ${current.path}. Registry ${paths.registry}; spec sheet locked numbers ${paths.spec}; testimonials ${paths.testimonials}; verbatim prose ${W}\\verbatim\\. For EVERY quantified claim, name, date, project fact, and quotation in the draft: find its proof id / testimonial id (from the HTML comments or by search) and confirm the value matches the locked value exactly and the source supports the claim as worded. Any claim without support, any value that differs, any quote without permission on-file → list it with the fix (correct value, or remove, or write around per gap decisions). Verdict pass only with zero unsupported items.`, {model:'opus', effort:'medium', phase:'Attack', label:`r${round} fact-check`, schema:FACTS}),
    () => agent(`Run: python "${W}\\voice\\metrics.py" "${current.path}" --client "Richmond" --client "the City" --json "${work}\\metrics_r${round}.json" and compare against the gates in ${paths.rubric} (gates array; hard gates must pass). Also run python "${W}\\work\\validate_v2.py" "${current.path}" --spec "${paths.spec}" --registry "${paths.registry}" --budget-pages ${S.budgetPages} --json "${work}\\validate_r${round}.json" if the script exists (skip docx checks if no docx yet). Return metrics, failing gates, verdict pass/fail.`, {model:'sonnet', effort:'low', phase:'Attack', label:`r${round} metrics`, schema:METRICS}),
  ])
  const ok = passes(reviews)
  log(`Attack round ${round}: ${reviews.map(r => r ? `${r.reviewer||'?'}=${r.verdict}` : 'null').join(', ')}`)
  if (ok) break
  current = await agent(`Revise the section draft to clear every finding. ${common}
Current draft: ${current.path}. Findings from five reviewers: ${JSON.stringify(reviews)}. Rules: fix blockers and majors fully; fix minors unless they conflict with the voice guide; never satisfy a compliance finding by adding a hedge or a placeholder — write the answer or apply the spec sheet's gap decision; never satisfy a fact-check finding by softening — use the locked value or remove the claim; keep the voice (re-read ${paths.voice}) and the page budget. Write to ${work}\\draft_synthesis_r${round+1}.md. Return path, angle "synthesis", prose word count, proof ids used, stories used, device counts.`, {model:SYNTH_MODEL, effort:'max', phase:'Attack', label:`revise r${round+1}`, schema:DRAFT})
}

phase('Render')
const render = await agent(`Render the final section. Draft: ${current.path}. Run: python "${W}\\work\\build_docx.py" "${current.path}" "${S.outDir}\\${S.outStem}.docx" --section-label "${args.sectionLabel}" --header "${args.headerText}" (this also writes ${S.outStem}_notes.docx for the Draft notes and any stripped tags). Then export to PDF via Word COM (win32com Word.Application, ExportAsFixedFormat 17) to ${work}\\${S.outStem}.pdf and count pages with fitz. Then run python "${W}\\work\\validate_v2.py" "${current.path}" "${S.outDir}\\${S.outStem}.docx" --spec "${paths.spec}" --registry "${paths.registry}" --budget-pages ${S.budgetPages} --json "${work}\\validate_final.json". Return docx path, notes path, page count, validator JSON, summary.`, {model:'sonnet', effort:'low', phase:'Render', label:'render + validate', schema:RENDER})

return { section: S.id, brief: brief.summary, drafts: drafts.map(d=>({angle:d.angle, words:d.words_prose})), ranking: ranked.map(r=>({angle:r.d.angle, mean:+r.mean.toFixed(2)})), rounds: round, final: current.path, reviews_final: reviews.map(r => r ? ({reviewer:r.reviewer, verdict:r.verdict, findings:(r.findings||r.unsupported||r.failing||[]).length}) : null), render }
